wrapperVersion=3.3.4
distributionType=bin
distributionUrl=https://repo.huaweicloud.com/repository/maven/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
wrapperUrl=https://repo.huaweicloud.com/repository/maven/org/apache/maven/wrapper/maven-wrapper/3.3.4/maven-wrapper-3.3.4.jar
