import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 同步脚本将 doc/README.md 转为 docs/index.md（slug=/docs），其余 01-12 按文件名排序，
// 故 autogenerated 顺序天然为 01→12，index 经 sidebar_position 置顶。
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
